name: 'Signed Commit'
description: 'GitHub Action to create signed commits from within a GitHub Action workflow'
author: 'qoomon'
branding:
  icon: git-commit
  color: black
inputs:
  message:
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v7
      env:
        INPUT_MESSAGE: ${{ inputs.message }}
      with:
        script: |
          await require('./path/to/script.js')({github, context, core})
